name: AWS CDK update check action
description: Check AWS CDK latest version
author: morning-code
branding:
  icon: 'trending-up'
  color: 'green'

outputs:
  latest_version:
    description: 'AWS CDK latest version'

runs:
  using: docker
  image: Dockerfile
